# frozen_string_literal: true

source 'https://rubygems.org'

gem 'cucumber'
gem 'jwt'
gem 'nonnative'
gem 'rbnacl'
gem 'rspec-expectations'
gem 'rspec-wait'
gem 'rubocop'
gem 'ruby-paseto'
gem 'solargraph'
