version: 2.1

jobs:
  build-service:
    docker:
      - image: alexfalkowski/go:1.22-ruby
      - image: grafana/mimir:latest
        command: -server.http-listen-port=9009 -auth.multitenancy-enabled=false -ingester.ring.replication-factor=1
    working_directory: ~/auth
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: mkcert -install
      - run: make create-certs
      - run: make dep
      - run: make lint
      - run: make proto-breaking
      - run: make sec
      - run: make features
      - run: make goveralls
      - store_artifacts:
          path: test/reports
    resource_class: large
  build-docker:
    docker:
      - image: alexfalkowski/go:1.22-ruby
    working_directory: ~/auth
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker
      - run: make build-docker
      - run: make trivy
    resource_class: large
  release:
    docker:
      - image: alexfalkowski/release:3.1
    working_directory: ~/auth
    steps:
      - checkout
      - run: release
    resource_class: large
  push-docker:
    docker:
      - image: alexfalkowski/go:1.22-ruby
    working_directory: ~/auth
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make push-docker
    resource_class: large

workflows:
  auth:
    jobs:
      - build-service
      - build-docker
      - release:
          context: gh
          requires:
            - build-service
            - build-docker
          filters:
            branches:
              only: master
      - push-docker:
          context: docker
          requires:
            - release
          filters:
            branches:
              only: master
