# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: auth/v1/service.proto for package 'Auth.V1'

require 'grpc'
require 'auth/v1/service_pb'

module Auth
  module V1
    module Service
      # Service for auth.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'auth.v1.Service'

        # GeneratePassword from meta.
        rpc :GeneratePassword, ::Auth::V1::GeneratePasswordRequest, ::Auth::V1::GeneratePasswordResponse
        # GeneratePassword from meta.
        rpc :GenerateKey, ::Auth::V1::GenerateKeyRequest, ::Auth::V1::GenerateKeyResponse
        # GenerateAccessToken from meta.
        rpc :GenerateAccessToken, ::Auth::V1::GenerateAccessTokenRequest, ::Auth::V1::GenerateAccessTokenResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
