# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth/v1/service.proto

require 'google/protobuf'

require 'google/api/annotations_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("auth/v1/service.proto", :syntax => :proto3) do
    add_message "auth.v1.GeneratePasswordRequest" do
      optional :length, :uint32, 1, json_name: "length"
    end
    add_message "auth.v1.GeneratePasswordResponse" do
      map :meta, :string, :string, 1
      optional :password, :message, 2, "auth.v1.Password", json_name: "password"
    end
    add_message "auth.v1.Password" do
      optional :plain, :string, 1, json_name: "plain"
      optional :hash, :string, 2, json_name: "hash"
    end
    add_message "auth.v1.GenerateKeyRequest" do
      optional :kind, :string, 1, json_name: "kind"
    end
    add_message "auth.v1.GenerateKeyResponse" do
      map :meta, :string, :string, 1
      optional :key, :message, 2, "auth.v1.Key", json_name: "key"
    end
    add_message "auth.v1.Key" do
      optional :public, :string, 1, json_name: "public"
      optional :private, :string, 2, json_name: "private"
    end
    add_message "auth.v1.GetPublicKeyRequest" do
      optional :kind, :string, 1, json_name: "kind"
    end
    add_message "auth.v1.GetPublicKeyResponse" do
      map :meta, :string, :string, 1
      optional :key, :string, 2, json_name: "key"
    end
    add_message "auth.v1.GenerateAccessTokenRequest" do
      optional :length, :uint32, 1, json_name: "length"
    end
    add_message "auth.v1.GenerateAccessTokenResponse" do
      map :meta, :string, :string, 1
      optional :token, :message, 2, "auth.v1.AccessToken", json_name: "token"
    end
    add_message "auth.v1.AccessToken" do
      optional :bearer, :string, 1, json_name: "bearer"
      optional :password, :message, 2, "auth.v1.Password", json_name: "password"
    end
    add_message "auth.v1.GenerateServiceTokenRequest" do
      optional :kind, :string, 1, json_name: "kind"
      optional :audience, :string, 2, json_name: "audience"
    end
    add_message "auth.v1.GenerateServiceTokenResponse" do
      map :meta, :string, :string, 1
      optional :token, :message, 2, "auth.v1.ServiceToken", json_name: "token"
    end
    add_message "auth.v1.ServiceToken" do
      optional :bearer, :string, 1, json_name: "bearer"
    end
    add_message "auth.v1.VerifyServiceTokenRequest" do
      optional :kind, :string, 1, json_name: "kind"
      optional :audience, :string, 2, json_name: "audience"
      optional :action, :string, 3, json_name: "action"
    end
    add_message "auth.v1.VerifyServiceTokenResponse" do
      map :meta, :string, :string, 1
    end
  end
end

module Auth
  module V1
    GeneratePasswordRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.v1.GeneratePasswordRequest").msgclass
    GeneratePasswordResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.v1.GeneratePasswordResponse").msgclass
    Password = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.v1.Password").msgclass
    GenerateKeyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.v1.GenerateKeyRequest").msgclass
    GenerateKeyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.v1.GenerateKeyResponse").msgclass
    Key = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.v1.Key").msgclass
    GetPublicKeyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.v1.GetPublicKeyRequest").msgclass
    GetPublicKeyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.v1.GetPublicKeyResponse").msgclass
    GenerateAccessTokenRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.v1.GenerateAccessTokenRequest").msgclass
    GenerateAccessTokenResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.v1.GenerateAccessTokenResponse").msgclass
    AccessToken = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.v1.AccessToken").msgclass
    GenerateServiceTokenRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.v1.GenerateServiceTokenRequest").msgclass
    GenerateServiceTokenResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.v1.GenerateServiceTokenResponse").msgclass
    ServiceToken = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.v1.ServiceToken").msgclass
    VerifyServiceTokenRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.v1.VerifyServiceTokenRequest").msgclass
    VerifyServiceTokenResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.v1.VerifyServiceTokenResponse").msgclass
  end
end
