# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth/v1/service.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/any_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("auth/v1/service.proto", :syntax => :proto3) do
    add_message "auth.v1.GeneratePasswordRequest" do
      map :meta, :string, :message, 1, "google.protobuf.Any"
    end
    add_message "auth.v1.GeneratePasswordResponse" do
      map :meta, :string, :message, 1, "google.protobuf.Any"
      optional :password, :message, 2, "auth.v1.Password", json_name: "password"
    end
    add_message "auth.v1.Password" do
      optional :plain, :string, 1, json_name: "plain"
      optional :hash, :string, 2, json_name: "hash"
    end
  end
end

module Auth
  module V1
    GeneratePasswordRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.v1.GeneratePasswordRequest").msgclass
    GeneratePasswordResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.v1.GeneratePasswordResponse").msgclass
    Password = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.v1.Password").msgclass
  end
end
